---
# Defines deployment design and assigns role to server groups

- hosts:
  - hummingbird

  gather_facts: false

  tags:
    - always

  tasks:
    # If we can't get python2 installed before any module is used we will fail
    # so just try what we can to get it installed
    - name: check for python2
      stat:
        path: /usr/bin/python
      ignore_errors: yes
      register: systempython2

    - name: install python2 for debian based systems
      raw: sudo apt-get -y install python-simplejson
      ignore_errors: yes
      when:
        - systempython2.stat.exists is undefined or systempython2.stat.exists == false

    - name: install python2 for fedora
      raw: sudo dnf -y install python creates=/usr/bin/python
      ignore_errors: yes
      when:
        - systempython2.stat.exists is undefined or systempython2.stat.exists == false

    - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] }}"

    - name: install required packages for fedora > 23
      raw: sudo dnf -y install python2-dnf libselinux-python ntp
      when:
        - ansible_distribution == 'Fedora'
        - ansible_distribution_major_version|int >= 23

- hosts: hummingbird
  gather_facts: false
  become: True
  roles:
    - ceph-defaults
    - ceph-common
    - ceph-config
    - ceph-mon

# Setup logging to centralized rsyslog server
- include: hummingbird-setup-logging.yml
